language: go
os:
  - linux
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
  - "ENABLE_TLS=false"
  - "LISTEN_ADDR=8080"
before_script:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
script:
  - gofmt -l ./ | grep -v vendor | wc -l | grep -q 0
  - go vet -v ./...
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - docker-compose -f dev-compose.yml up --build -d mockitout
  - curl -k https://localhost:443/hi | python -mjson.tool
after_success:
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
