version: "3"
services:
  mockitout:
    build: .
    ports:
      - "443:8443"
    command: --debug 
    environment:
      - "LISTEN_ADDR=0.0.0.0:8443"
  tests:
    build: .
    working_dir: /go/src/github.com/madflojo/mockitout
    entrypoint: go test -v -covermode=count -coverprofile=/tmp/coverage/coverage.out ./...
    volumes:
      - "./coverage:/tmp/coverage"

volumes:
  coverage:
